name: CI / Deploy

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches:
      - master
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell

      - name: Install Dependencies
        run: yarn

      # Runs a set of commands using the runners shell
      - name: Run ESLint
        run: yarn eslint . --fix --max-warnings=0
        
  build_and_preview:
    needs: CI
    runs-on: ubuntu-latest
    if: │'${{ github.event.pull_request.head.repo.full_name == github.repository }}' && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - run: yarn && yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FOODIELAND_F0EB0 }}'
          projectId: foodieland-f0eb0
          
  build_and_deploy:
    needs: CI
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - run: yarn && yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FOODIELAND_F0EB0 }}'
          channelId: live
          projectId: foodieland-f0eb0
